### ISSUE TITLE
Feature Request: Be able to set `MIN_GRID_LENGTH`

### ISSUE THREAD

**Issue by KeroZhai** [AhmedAyachi/LinkerLine#10]
See [May it be possible to set the minimal grid length property as parameter? ](https://github.com/anseki/leader-line/issues/256)

**Comment by AhmedAyachi** [comment]
hello, anseki claims that changing that value will "break the logic of code (e.g. infinite loop)".
Can I ask why you need such feature and could your problem be solved other way ?

**Comment by KeroZhai** [comment]
Sorry for the late reply, the reason I need to set `MIN_GRID_LENGTH` is that lines are rendered not as expected. 

I use LinkerLine to draw dependency lines in a Gantt Chart, and I don' want the line over the gantt bar. Please check this demo: https://jsfiddle.net/hk2onjuw/6/.

**Comment by AhmedAyachi** [comment]
@KeroZhai check the beta branch, is that what you need ?

**Comment by AhmedAyachi** [comment]
I'm closing this as minGridLength prop has been added starting with v1.6.0.
Hope this is what you're asking for @KeroZhai.

**Comment by KeroZhai** [comment]
Much appreciated! With this update I can get rid of my pnpm patch.

By the way, thanks for this project and all your effort!
