### ISSUE TITLE
Add support to vanilla javascript (umd)

### ISSUE THREAD

**Issue by YKSing** [AhmedAyachi/LinkerLine#11]
It is possible to use `webpack` to generate a minified umd js file to support vanilla javascript.

1. Git this project to local
2. `npm install --save-dev webpack webpack-cli`
3. Create the file `webpack.config.js`
```javascript
module.exports = {
  output: {
    library: {
      type: "umd",
      name: "LinkerLine",
      export: ['default'],
    },
    filename: 'index.min.js',
  },
};
```
4. run `npx webpack`

You will get the minified js file in /dist and use it without module.

**Comment by AhmedAyachi** [comment]
check the beta branch is that what you're looking for.
[linkerline.min.js](https://raw.githubusercontent.com/AhmedAyachi/LinkerLine/beta/dist/linkerline.min.js)
