### ISSUE TITLE
Feature Request: “custom” Property

### ISSUE THREAD

**Issue by kdagnan** [AhmedAyachi/LinkerLine#6]
Hi,

First of all, let me thank you for continuing the original LeaderLine project, and adding great features like parent and LinkerChain (plus types!). This has saved my team so much time, not requiring us to use a massive diagramming library with millions of options to achieve our “flowchart” designs.

Now, I would like to request a “custom” property on the LinkerLine (and LinkerChain, Label, etc) options. Similar to [HighCharts custom property](https://api.highcharts.com/highcharts/plotOptions.series.custom), it would allow you to store additional data on the LinkerLine for use later. 

We have a lot of interactivity that shows/hides certain things based on other conditions and having some data on the LinkerLine would be much more straightforward than how we’re having to associate these currently.

Thank you!

**Comment by AhmedAyachi** [comment]
can you provide a code snippet of how you want the feature to be used from dev experience perspective.

**Comment by kdagnan** [comment]
Something like this is what we're hoping to achieve:
```js
this.linkerLines = [];

initializeLines(){
     //Inside Loop
     this.linkerLines.pushObject(
        new LinkerLine({ 
           start: document.querySelector(`#flow-step-${fromSteptepId}`), 
           end: document.querySelector(`#flow-step-${toSteptepId}`),
           custom: {
               toStepType: 'ACCOUNT',
               fromStepType: 'PERSON'
           }
       })
   );
}

onHover(){
    this.linkerLines.forEach(linkerLine => {
        if(linkerLine.custom.toStepType === 'ACCOUNT') {
             linkerLine.hide();      
        }
    });
}
```

The alternative would be to either store this data as an attribute on the start/end elements for retrieval later or to keep a separate map of linkerLine to custom properties.

**Comment by AhmedAyachi** [comment]
why not doing this:
``` 
this.linkerLines = [];

initializeLines(){
     //Inside Loop
    const line=new LinkerLine({ 
        start: document.querySelector(`#flow-step-${fromSteptepId}`), 
        end: document.querySelector(`#flow-step-${toSteptepId}`),
    });
    line.custom={
        toStepType: 'ACCOUNT',
        fromStepType: 'PERSON'
    }
     this.linkerLines.pushObject(line);
}

onHover(){
    this.linkerLines.forEach(linkerLine => {
        if(linkerLine.custom.toStepType === 'ACCOUNT') {
             linkerLine.hide();      
        }
    });
}
```

**Comment by kdagnan** [comment]
I do not know why i didn't think to try that. Thank you
