### ISSUE TITLE
Line is draw in the constructor even when hidden

### ISSUE THREAD

**Issue by PeterMRichards** [AhmedAyachi/LinkerLine#7]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `linkerline@1.4.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/linkerline/src/index.js b/node_modules/linkerline/src/index.js
index 2536411..370f9d2 100644
--- a/node_modules/linkerline/src/index.js
+++ b/node_modules/linkerline/src/index.js
@@ -19,7 +19,11 @@ export default class LinkerLine extends LeaderLine {
                 parent.style.position="relative";
             }
             parent.appendChild(this.element);
-            this.position();
+            
+            if (!props.hide) {
+                this.position();
+            }
+
             setLinePlugStyle(this);
         }
     }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by AhmedAyachi** [comment]
did you use "hide" or "hidden" prop ? cause hide prop is renamed to hidden

**Comment by PeterMRichards** [comment]
Hi, I'm using the correct variable, because props.hide is set as Boolean(props.hidden);

I'm just looking to avoid unnecessary calls to this.position for performance reasons.
Also looking to do this with setOptions.

**Comment by AhmedAyachi** [comment]
@PeterMRichards  are you facing any performance issues for now ?

**Comment by PeterMRichards** [comment]
I have not done extensive testing.
My use case is targeted for phones & I've tested on my 8 year old phone Samsung S7.
And it suffers quite a bit.

But my use case is a bit extreme, drawing > 30 lines on average.
And they are repositioned each frame.
The position function is a bottle neck when I profile it.

To mitigate that, I pool the lines for the camera's viewport and only draw those.
And I hide the lines when the camera is moving a lot & when its slowed down I show/reveal a couple of lines at a time per frame.

It does gain some frames when position is not called for hidden lines.
In general it might be better if I used some Web GL based framework for my use case of lines.
But at the moment using linker line is more straight forward. 👍

**Comment by AhmedAyachi** [comment]
@PeterMRichards 
Thanks for sharing, The improvement you provided is going to be implemented in the next version.
In addition, the performance issue you're facing is due to, first the mobile environment and second, the original project is using the left and top properties to position lines instead of a transformation (translate) which is less performant and I'm planning to dig into the original code and figure out a way to change that.
