### ISSUE TITLE
Cannot Update Color

### ISSUE THREAD

**Issue by kdagnan** [AhmedAyachi/LinkerLine#8]
"TypeError: Cannot set property color of #<LinkerLine> which has only a getter".

Per the original LeaderLine documentation this should be possible. Removing the getter in the LinkerLine class seems to fix the issue with no consequences that I have noticed.

<img width="860" alt="Screenshot 2024-08-07 at 11 52 03 AM" src="https://github.com/user-attachments/assets/e8fa5849-7d7b-434a-9259-7eb358b93cda">

**Comment by AhmedAyachi** [comment]
that's made intentionally to provide a standard and a single way to update options and that through setOptions
