### ISSUE TITLE
当我的microApp子应用使用linker-line时，会被抛出一个错误 LeaderLine.js:2  A disconnected element was passed.

### ISSUE THREAD

**Issue by DongZeMan** [AhmedAyachi/LinkerLine#9]
最近开始用microApp整合之前的项目，当嵌入其中一个使用了linkerline的子应用时，控制台抛出来一个错误
![image](https://github.com/user-attachments/assets/95d15455-5182-4684-8f6c-052632446df9)
能告知下是什么原因吗？

**Comment by AhmedAyachi** [comment]
The first error "a disconnected element was passed" indicates that the start/end element of one of the lines is no longer present in the dom.
can you send me a snippet of the code throwing these errors please.

**Comment by DongZeMan** [comment]
I enclose a picture for you
![image](https://github.com/user-attachments/assets/56101f98-1ba0-4405-9e8a-5b56d360cd43)

**Comment by AhmedAyachi** [comment]
are you sure you're not removing the elements at some point afterwards ?

**Comment by DongZeMan** [comment]
是的，但是我目前是作为microapp的子应用，才导致了这个问题，所以想咨询一下有没有什么解决方案

**Comment by AhmedAyachi** [comment]
still not understood, are you saying there is a bug in linkerline or in the original leader-line project that you would like me to fix it ?

**Comment by DongZeMan** [comment]
不是的，我只是想知道问题是出在linkerline还是microapp

**Comment by DongZeMan** [comment]
然后还有就是想知道您有没有碰到过类似问题，如果有的话想请教一下解决方案

**Comment by AhmedAyachi** [comment]
as you can see the error file is LeaderLine.js, that's the original project code, so the issue is either with your app or leader-line's.

**Comment by AhmedAyachi** [comment]
yes I did regenerate it just a sec ago, i created a line and after that called line.start.remove() and tried to reposition the line.
As I told you, start/end element is no longer in the dom.

**Comment by DongZeMan** [comment]
但是我当前项目不作为microapp的子应用，这个项目单独运行是没有问题的，并且我自己并没有对dom进行任何操作，所以我也不知道具体问题出在哪边

**Comment by DongZeMan** [comment]
但是我在new LinkerLine之前对parent，start，end都进行了判断，判断它们都不为null之后，再new LinkerLine，报错还是一样，我也尝试过在setTimeout中去执行，延时为5000ms，依旧是报错，报错内容都一样

**Comment by AhmedAyachi** [comment]
can you share your code in stackblitz or something similar ?

**Comment by DongZeMan** [comment]
github仓库可以吗

**Comment by AhmedAyachi** [comment]
if it's public why not, just send the link

**Comment by DongZeMan** [comment]
https://github.com/DongZeMan/micro-app-problem-demo.git

**Comment by DongZeMan** [comment]
代码内容不是最新的，但是同样能复现出对应的效果

**Comment by AhmedAyachi** [comment]
faced this error App.vue:41 
 Uncaught TypeError: Cannot read properties of undefined (reading 'addGlobalDataListener')
commented line 40-41 in App.vue and the linkerline is getting instantiated. can't see what you're facing exactly.
![localhost_5678_child1_](https://github.com/user-attachments/assets/69945cbd-7b35-4422-bd59-f30ba3b424e7)

**Comment by DongZeMan** [comment]
因为这个项目我是作为microapp的子系统去嵌入的，您现在应该是单独运行这个项目，所以需要注释掉一些代码，注释掉40行到42行的代码就可以单独运行了，但是我希望的是通过base-project-vite无访问child-project-vite-1，也就是http://localhost:5173/child-app-1这种形式去访问http://localhost:5678，这种方式下则会复现之前的报错

**Comment by DongZeMan** [comment]
复现步骤是，先运行child-project-vite-1，然后再运行base-project-vite，然后访问http://localhost:5173，再点击第一个菜单，打开控制台就能看到报错了

**Comment by AhmedAyachi** [comment]
I get it now, when accessing the micro-app server directly np but when accessin it from the base app, it generates that error.
It seems to be an issue with the leader-line code itself, same error when using leader-line I guess ?

**Comment by DongZeMan** [comment]
如果不使用linkerline，使用leaderline，也会有一模一样的错误

**Comment by DongZeMan** [comment]
不管使用leaderline还是linkerline，child-project-vite-1自己单独运行都不会报错

**Comment by DongZeMan** [comment]
![image](https://github.com/user-attachments/assets/47b8235a-affa-4a40-9cbd-8c22c6883852)
执行new LinkerLine之前都是可以打印出DOM元素的，但是不知道为什么new LinkerLine就开始报错了
![image](https://github.com/user-attachments/assets/43d31994-36c4-440c-a75d-2000afebcb0e)

**Comment by AhmedAyachi** [comment]
Then the issue has nothing to do with the linkerline but with the leaderline itself as linkerline is built on top of the latter.
I'll try to investigate this, meanwhile, you do the same.
But why are you trying to show a subapp inside another app, never seen this tbh.

**Comment by DongZeMan** [comment]
好的，最开始我准备询问leaderline的作者，但是leaderline的issue已经不让新建了，所以我没有办法找到作者了，至于为什么要在一个应用程序中显示一个子程序，那是因为我们需要做一个微应用的站点，就是要在主应用中去访问一些接入的子应用程序

**Comment by AhmedAyachi** [comment]
can you use an iframe instead and see if that works, just to test it.

**Comment by DongZeMan** [comment]
使用iframe嵌入的话，不会报错

**Comment by DongZeMan** [comment]
但是我们技术栈要求是microapp

**Comment by DongZeMan** [comment]
可是如果使用iframe，那就脱离了microapp的沙箱了

**Comment by AhmedAyachi** [comment]
What do you mean by sandbox ?
The iframe has a sandbox attribute if that what you're referring to.
I'm quite busy at the moment but I'm planning to take a look at it, you can do so but it's a little headache as you need to dig into the LeaderLine.js file and then submit a PR.

**Comment by DongZeMan** [comment]
不是，我说的是micro-app的沙箱，并不是iframe自己的沙箱

**Comment by DongZeMan** [comment]
我已经定位到问题了，问题并不是出在leaderline本身，而是出在micro-app

**Comment by AhmedAyachi** [comment]
happy to hear that.
Just out of curiosity, what was the issue ?
